version: '2'
services:
  redis:
    container_name: unms-redis
    image: redis:3.2.3
    restart: always
    volumes:
      - ./data/redis:/data/db
    ports:
      - 6379:6379
    command: "redis-server --appendonly yes --dir /data/db/"

  mongo:
    container_name: unms-mongo
    image: mongo:3.2.11
    restart: always
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017

  unms:
    container_name: unms
    image: ubnt/unms:${VERSION}
    restart: always
    links:
      - redis
      - mongo
    volumes:
      - ./data/cert:/home/app/unms/cert
      - ./data/images:/home/app/unms/public/site-images
      - ./data/config-backups:/home/app/unms/data/config-backups
      - ./data/unms-backups:/home/app/unms/data/unms-backups
    ports:
      - 80:8080
      - 443:8443
    environment:
      - PROD=${PROD}
      - PUBLIC_HTTPS_PORT=443
      - DEMO=${DEMO}

